config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/dev-admin', as: 'rails_admin'
  ActiveAdmin.routes(self)
  /# Implement subdomain for blog #/

  # constraints Subdomain do ----> 'Blog'
  # get "/" => redirect { |params| "http://www.winterworks.com" }
  # get '*path' => redirect('/')
  # get '*path#*path' => redirect('/')
  # end

  # admin routes

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
}, skip: [:sessions, :registrations]


  root :to => "index#default"
  get '/dashboard/' => 'users#index', :as => 'user_root' # manage projects from here? idk yet -- definitely view orders and stuff

  # Devise 

  devise_scope :user do

    ## MARK: Add custom forget password button

    get    'register', to: 'devise/registrations#new',    as: :new_user_registration
    post   '/account',  to: 'devise/registrations#create'
    get    '/account/cancel', to: 'devise/registrations#cancel', as: :cancel_user_registration

    get    '/account',  to: 'devise/registrations#edit',   as: :edit_user_registration
    put    '/account',  to: 'devise/registrations#update'
    patch  '/account',  to: 'devise/registrations#update', as: :user_registration
    delete '/account',  to: 'devise/registrations#destroy'
    
    get    'login',  to: 'devise/sessions#new',     as: :new_user_session
    post   'login',  to: 'devise/sessions#create',  as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  # Extraneous routes --> Static

  get '/pricing/' => 'index#pricing', as: 'pricing'
  get '/about/' => 'index#about', as: 'about'
  get '/blog/' => 'index#blog', as: 'view_blog'
  get '/support/' => 'index#support', as: 'support'

  # Extraneous routes --> Dynamic/Static

  get '/browse/' => 'index#discover', as: 'social_feed'
  get '/browse/posts/' => 'posts#list_global', as: 'posts_feed'

  get '/browse/users/' => 'users#list', as: 'list_users'
  get '/browse/talent/' => 'users#requests', as: 'hireable_users'

  # Extraneous routes --> Project Management

  get '/browse/projects/:q' => "projects#filter_by_project_type", :as => 'filter_proj_by_type'
  
  match '/edit-project/:uuid/:id' => 'edit_project#show', :via => [:get], as: 'edit_project'


  get '/browse/projects/' => 'projects#feed', as: 'view_projects'
  get '/new/project/' => 'projects#new', as: 'create_new_project'
  post '/submit/project/' => 'projects#create', as: 'submit_new_project'
  match '/project/:uuid/' => 'projects#view', :via => [:get], as: 'view_singular_project'

  # Extraneous routes --> Commission Management

  match '/@:username/commission/:uuid/' => 'commissions#view', :via => [:get], as: 'view_singular_commission'
  get '/browse/commissions/' => 'commissions#list', as: 'list_commissions'
  get '/new/commissions/' => 'commissions#create', as: 'create_new_commission'
  post '/submit/commission/' => 'commissions#new', as: 'submit_new_commission'

  # Extraneous routes --> Upload, Creation + Onboarding

  get '/submit/' => 'posts#upload', as: 'upload_post'
  post '/submit/' => 'posts#new', as: 'submit_new_post'
  match '/posts/:uuid/' => 'posts#view', :via => [:get], as: 'view_this_post'
  match '/posts/:uuid/like' => 'posts#like', :via => [:post], as: 'like_post'
  match '/posts/:uuid/comment' => 'comments#create', :via => [:post], as: 'create_new_comment'

  # Extraneous routes --> Public User Showcase
  match '/@:username/follow' => 'followerships#follow_user', :via => [:post], as: 'follow_this_user'


  match '/@:username/following' => 'followerships#following', :via => [:get], as: 'user_following'
  match '/@:username/followers' => 'followerships#followers', :via => [:get], as: 'user_followers'
  match '/@:username/likes' => 'users#list_likes', :via => [:get], as: 'list_this_users_likes'


  match '/@:username' => 'users#show', :via => [:get], as: 'view_profile'
  match '/@:username/about' => 'users#more_info', :via => [:get], as: 'about_profile'

  get '/profile/edit/' => 'users#edit_profile', as: 'edit_profile'
  patch '/profile/edit/' => 'users#update_profile', as: 'update_profile'

  get '/i/notifications/' => 'users#notifications', as: 'social_notifications'

  # Extraneous routes --> Commissions

  match '/@:username/portfolio/' => 'portfolio#show', :via => [:get], as: 'view_user_commission_page'
  match '/@:username/portfolio/edit/' => 'portfolio#edit', :via => [:get], as: 'edit_user_commission_page'
  match '/@:username/portfolio/edit/' => 'portfolio#update', :via => [:patch], as: 'update_user_commission_page'
  
  # Extraneous routes --> Manufactory Checkout
  
  resources :manufactory

  # Extraneous routes --> Orders

  match '/checkout/commission/:uuid/:id' => 'orders#new', :via => [:get], as: 'place_new_commission_order'

  # Extraneous routes --> Dynamic Project Space

  # Extraneous routes --> Payments

  get '/account/billing', to: 'users#payments', as: 'edit_billing_methods'

end

app/views/index/about.html.erb
<%= render 'shared/navbar' %>

<h1>About Winterworks</h1>

<p>Winterworks is</p>

app/views/index/blog.html.erb
<%= render 'shared/navbar' %>

<p>coming soon</p>

app/views/index/default.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= content_for :title, 'Winterworks' %></title>
    <%= stylesheet_link_tag 'index' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>

    <%= render 'shared/navbar' %>
    <p>Welcome to Winterworks.</p>

    <div class="showcase">
        <span>Create new projects and work with new people. Get paid for your art!</span>
    </div>

    <h2> Recent User Posts </h2>

    <% @users.each do |user| %>

        <% user.posts.each do |post| %>

        <% if post.post_type == "image" %>


            	<% if post.post_image.attached? %>
            		<div class="user-post-card"><%= image_tag post.post_image, style: 'height:40px;width:40px;' %> <br>     </div>
				<% end %>
   

        <% else %>
            no image posts
        <% end %>
            <!-- if user has posts show them -->
        <% end %>
    <% end %>

    <!-- Page Art Wallpaper -->

    <div class="page__art">
        <div class="art-wrapper">
            <div class="art"></div>
        </div>
    </div>
</body>
</html>

app/views/index/discover.html.erb
<!doctype html>
<head>
</head>
<body>
<%= render 'shared/navbar' %>

<h1>Social Feed</h1>
<p>Find artists and their works</p>
   
<%= form_tag(root_path method: :get) do %>
    <%= text_field_tag :user, nil, {:placeholder=>"Search...", :class => 'filter-search-module'}  %>
    <%= submit_tag 'Search', class: 'filter-search-btn' %>
<% end %>
<br>

<h3>Popular Art</h3>

<% @users.each do |user| %>

    <% user.posts.each do |post| %>

        <% if post.post_image.attached? %>
            <% if post.post_type == "image" %>

                <div class="user-post-card">
                <%= image_tag post.post_image %>
                Posted by @<%= post.user.username %> on <%= post.created_at %>
                <br>
                 <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p> 
                 <%= button_to "Like this post", like_post_path(post.uuid), :method=> :post %>
                 <li><%= link_to "View this post", view_this_post_path(post.uuid) %></li>
                </div>
            <% end %>
            <!-- if user has posts show them -->
        <% end %>
    <% end %>
<% end %>
<br>
<%= link_to "View all user posts", posts_feed_path %> <br>

<br>

<h3>New Users</h3>

<% @users.each do |user| %>
    <div class="user-card">
        <div class="inner-heading">
        <% if user.profile_image.attached? %>
            <%= image_tag user.profile_image, style: 'height:60px;width:60px;' %>
         <!-- show image if attached, if not use default-->
        <% else %>
	        <img src="https://d3pknrmpgdk5xi.cloudfront.net/assets/avatars/defaults/2-35169e7a0a76d93a0887f051aab8c51f02f050d919ff14a98dbc26179774b374.png" height="60" alt="<% user.username %>" class="nav-avatar">
        <% end %>
         <p><%= user.first_name %> <%= link_to('@' + user.username, view_profile_path(user.username), class: 'ok') %> </p>
    </div>
    </div>
    <br>
<% end %>


<%= link_to('View all users', list_users_path, class: 'ok') %> <br>

<!-- 

EVERY POST IS DISPLAYED IN BITS. TALENT/PROJECT/COMMISIONS HAVE THEIR OWN SEARCH PANELS
-->
</body>
</html>

app/views/index/pricing.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= content_for :title, 'Simple Pricing - Winterworks' %></title>
    <%= stylesheet_link_tag 'pricing' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>

<body>
    <div class="app">
        <%= render 'shared/navbar' %>
        <div class="features">
            <h1>Simple Pricing.</h1>
            <p>Free</p>
            <a>You currently have this</a>
            <p>$4.99/month</p>
            <a href="#">Upgrade your account to this plan</a>
            <p>$9.99/month</p>
            <a href="#">Upgrade your account to this plan</a>
            <p>$19.99/month</p>
            <a href="#">Upgrade your account to this plan</a>
        </div>
    </div>
</body>

</html>

app/views/index/support.html.erb
<%= render 'shared/navbar' %>

<h1>Support</h1>