config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/dev-admin', as: 'rails_admin'
  ActiveAdmin.routes(self)
  /# Implement subdomain for blog #/

  # constraints Subdomain do ----> 'Blog'
  # get "/" => redirect { |params| "http://www.winterworks.com" }
  # get '*path' => redirect('/')
  # get '*path#*path' => redirect('/')
  # end

  # admin routes

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
}, skip: [:sessions, :registrations]


  root :to => "index#default"
  get '/dashboard/' => 'users#index', :as => 'user_root' # manage projects from here? idk yet -- definitely view orders and stuff

  # Devise 

  devise_scope :user do

    ## MARK: Add custom forget password button

    get    'register', to: 'devise/registrations#new',    as: :new_user_registration
    post   '/account',  to: 'devise/registrations#create'
    get    '/account/cancel', to: 'devise/registrations#cancel', as: :cancel_user_registration

    get    '/account',  to: 'devise/registrations#edit',   as: :edit_user_registration
    put    '/account',  to: 'devise/registrations#update'
    patch  '/account',  to: 'devise/registrations#update', as: :user_registration
    delete '/account',  to: 'devise/registrations#destroy'
    
    get    'login',  to: 'devise/sessions#new',     as: :new_user_session
    post   'login',  to: 'devise/sessions#create',  as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  # Extraneous routes --> Static

  get '/pricing/' => 'index#pricing', as: 'pricing'
  get '/about/' => 'index#about', as: 'about'
  get '/blog/' => 'index#blog', as: 'view_blog'
  get '/support/' => 'index#support', as: 'support'

  # Extraneous routes --> Dynamic/Static

  get '/browse/' => 'index#discover', as: 'social_feed'
  get '/browse/posts/' => 'posts#list_global', as: 'posts_feed'

  get '/browse/users/' => 'users#list', as: 'list_users'
  get '/browse/talent/' => 'users#requests', as: 'hireable_users'

  # Extraneous routes --> Project Management

  get '/browse/projects/:q' => "projects#filter_by_project_type", :as => 'filter_proj_by_type'
  
  match '/edit-project/:uuid/:id' => 'edit_project#show', :via => [:get], as: 'edit_project'


  get '/browse/projects/' => 'projects#feed', as: 'view_projects'
  get '/new/project/' => 'projects#new', as: 'create_new_project'
  post '/submit/project/' => 'projects#create', as: 'submit_new_project'
  match '/project/:uuid/' => 'projects#view', :via => [:get], as: 'view_singular_project'

  # Extraneous routes --> Commission Management

  match '/@:username/commission/:uuid/' => 'commissions#view', :via => [:get], as: 'view_singular_commission'
  get '/browse/commissions/' => 'commissions#list', as: 'list_commissions'
  get '/new/commissions/' => 'commissions#create', as: 'create_new_commission'
  post '/submit/commission/' => 'commissions#new', as: 'submit_new_commission'

  # Extraneous routes --> Upload, Creation + Onboarding

  get '/submit/' => 'posts#upload', as: 'upload_post'
  post '/submit/' => 'posts#new', as: 'submit_new_post'
  match '/posts/:uuid/' => 'posts#view', :via => [:get], as: 'view_this_post'
  match '/posts/:uuid/like' => 'posts#like', :via => [:post], as: 'like_post'
  match '/posts/:uuid/comment' => 'comments#create', :via => [:post], as: 'create_new_comment'

  # Extraneous routes --> Public User Showcase
  match '/@:username/follow' => 'followerships#follow_user', :via => [:post], as: 'follow_this_user'


  match '/@:username/following' => 'followerships#following', :via => [:get], as: 'user_following'
  match '/@:username/followers' => 'followerships#followers', :via => [:get], as: 'user_followers'
  match '/@:username/likes' => 'users#list_likes', :via => [:get], as: 'list_this_users_likes'


  match '/@:username' => 'users#show', :via => [:get], as: 'view_profile'
  match '/@:username/about' => 'users#more_info', :via => [:get], as: 'about_profile'

  get '/profile/edit/' => 'users#edit_profile', as: 'edit_profile'
  patch '/profile/edit/' => 'users#update_profile', as: 'update_profile'

  get '/i/notifications/' => 'users#notifications', as: 'social_notifications'

  # Extraneous routes --> Commissions

  match '/@:username/portfolio/' => 'portfolio#show', :via => [:get], as: 'view_user_commission_page'
  match '/@:username/portfolio/edit/' => 'portfolio#edit', :via => [:get], as: 'edit_user_commission_page'
  match '/@:username/portfolio/edit/' => 'portfolio#update', :via => [:patch], as: 'update_user_commission_page'
  
  # Extraneous routes --> Manufactory Checkout
  
  resources :manufactory

  # Extraneous routes --> Orders

  match '/checkout/commission/:uuid/:id' => 'orders#new', :via => [:get], as: 'place_new_commission_order'

  # Extraneous routes --> Dynamic Project Space

  # Extraneous routes --> Payments

  get '/account/billing', to: 'users#payments', as: 'edit_billing_methods'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
# id			:integer		not null, primary_key
# name			:string(255)
# username      :string(255)
#
# bio:text
# location: string
# website: string --- URL REGEX
#
# paid_member: boolean (if yes, access certain features depending on....
#
# member_type: integer ---- {0: Creator ($19.99), 1: Free, 2: Basic ($4.99), 3: Full ($9.99)}
#
#

class User < ApplicationRecord

  enum member_type: { full: 3, basic: 2, free: 1, creator: 0}

  # Attachments & Associations

  has_many :followers, :class_name => 'Following', :foreign_key => 'user_id'
  has_many :following, :class_name => 'Following', :foreign_key => 'follower_id'

  has_one_attached :profile_image

  has_many :likes, dependent: :destroy #post likes
  has_many :posts, dependent: :destroy
  has_many :liked_posts, :through => :likes, :source => :post #@user.liked_posts

  has_many :commissions, dependent: :destroy
  has_many :projects, dependent: :destroy

  # User Profile

  has_one :profile, dependent: :destroy
  after_create :build_profile
  accepts_nested_attributes_for :profile

  # Commission Portfolio
  has_one :portfolio, dependent: :destroy
  after_create :build_portfolio
  accepts_nested_attributes_for :portfolio

  # Regex Expressions

  VALID_URL_REGEX = /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\z/ix

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,
         :trackable

  # Validations

  validates(:email, presence: true, uniqueness: { case_sensitive: false })

  validates(:encrypted_password, presence: true, length: { minimum: 8 })

  validates(:member_type, presence: true)

  validates(:username, presence: true, length: 3..16, uniqueness: { case_sensitive: false })

  validates(:first_name, presence: true, length: { maximum: 50 })
  
  validates(:last_name, presence: true, length: { maximum: 50 })

  private
    def build_profile
      self.profile = Profile.create(:user => self)
    end 

    def build_portfolio
      self.portfolio = Portfolio.create(:user => self)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  after_action :after_sign_up_path_for, if: :devise_controller?, only: [:create]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  protected

  def after_sign_in_path_for(resource)    
    if current_user.admin?      
      admin_root_path  
    else       
      edit_profile_path   
    end       
  end 
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController   
    skip_before_action :authenticate_user!, :only => [:show, :list]

    def index
        @user = current_user
        @projects = @user.projects
    end

    def notifications
        #
    end

    def show
        x = current_user
        @user = User.find_by_username(params[:username])
        
        @z = Following.where(user: @user, follower: x).first

        if @user == nil 
            redirect_to list_users_path, notice: 'The user you\'ve specified does not exist.'
        end
    end

    def more_info
        @user = User.find_by_username(params[:username])

        if @user == nil 
            redirect_to list_users_path, notice: 'The user you\'ve specified does not exist.'
        end

        @profile = @user.profile
    end

    def list
        @users = User.all.order(created_at: :desc).limit(10)
    end

    def edit_profile
        @user = current_user
    end

    def update_profile
        @user = current_user
        @profile = current_user.profile
        
        if @user.update_attributes(profile_params)
          redirect_to view_profile_path(@user.username), notice: 'User settings were saved.'
        else
            error_msgs = ['THROW ERROR']
            error_msgs << [@user.errors.full_messages]
            redirect_to edit_profile_path, notice: 'Invalid entry, try again!'
        end
    end

    def requests
        @users = User.all.order(created_at: :desc)
    end

    def list_likes
        @user = User.find_by_username(params[:username])
        @likes = @user.likes.count
    end

    private

        def profile_params
            params.require(:user).permit(:first_name, :last_name, :bio, :location, :profile_image, :website, profile_attributes: [:status, :taking_requests, :id])
        end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit_profile.html.erb
<%= render 'shared/navbar' %>

<div class="top-bar">

	<%= link_to('Go back to your profiles', view_profile_path(@current_user.username), class: 'ok') %> 

</div>

<h1>Update User Profile</h1>

<%= form_for(@user, url: update_profile_path, local: true) do |f| %>

<%= f.fields_for :profile do |p_f| %>
  <%= p_f.label "Availability" %>
  <%= p_f.select :status, Profile.statuses.keys %>
  <br>
  <%= p_f.label "Do you want to take commissions?" %>
  <%= p_f.check_box :taking_requests %>
<% end %> <br>

<%= f.label :first_name %>:
  <br>
  <%= f.text_field :first_name, class: 'form-control' %>

<br>

<%= f.label :last_name %>:
  <br>
<%= f.text_field :last_name, class: 'form-control' %>


<br>

<%= f.label :bio %>:
<br>
<%= f.text_area :bio, :cols => "30", :rows => "5" %>

<br>

<%= f.label :location %>:
  <br>
<%= f.text_field :location, class: 'form-control', autocomplete: "location" %>

<br>

<% if @current_user.profile_image.attached? %>
	<%= image_tag @current_user.profile_image %>
<% end %>

<%= f.label :profile_image %>:
  <br>

<%= f.file_field :profile_image, class: 'image-' %><br>

<br>

<%= f.label :website %>:
  <br>

<%= f.text_field :website, class: 'website-link' %><br>

<br>

  <%= f.submit "Save changes"%>
<% end %>

app/views/users/index.html.erb
<!-- ./dashboard -->

<!DOCTYPE html>
<html>
<head>
    <title><%= content_for :title, 'Dashboard - Winterworks' %></title>
    <%= stylesheet_link_tag 'users' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>

    <%= render 'shared/navbar' %>

    <div class="app">

    <span><h1>Dashboard</h1>

    <% if user_signed_in? %>

        <%= link_to('Account Settings', edit_user_registration_path) %>
        <br>
        <%= link_to('Your Profile', view_profile_path(current_user.username)) %>
        <br>  
        <%= link_to('Edit your profile', edit_profile_path) %>  
        <br>  
        <%= link_to('Payment Settings', edit_billing_methods_path) %>
        <br>    
 
    <% end %>

    <h4>Signed in as... <%= current_user.first_name %></h4>
    <p>Welcome to the dashboard..it's a work in progress.</p>

    <h2>Projects</h2>

    <% if @projects.empty? %>
        <p>nothing here yet</p>
    <% else %>
        <% @projects.each do |project| %>
        <li><%= project.title %></li>
        <%= link_to "View this project", view_singular_project_path(project.uuid) %>
        <br>
        <% end %>
    <% end %>
 
    <br>

    <h2>Orders</h2>
    <p>nothing here yet</p>

    <br>

    <h2>Payouts</h2>
    <p>nothing here yet</p>
    
    </span>

    <br>

    <!-- link to log out -->
    <%= link_to "Log out", destroy_user_session_path, :method => :delete, class: 'vacant-btn' %>

    </div>

    <!-- background -->
        <div class="page__art">
        <div class="art-wrapper">
            <div class="art-alt"></div>
        </div>
    </div>
</body>
</html>

app/views/users/list.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= content_for :title, 'Users — Winterworks' %></title>
    <%= stylesheet_link_tag 'users' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
    <body>
    <%= render 'shared/navbar' %>

    <div class="heading">
            <h1>List of Winterworks users</h1>
    </div>

<% @users.each do |user| %>
    <div class="user-card">
        <div class="inner-heading">
        <% if user.profile_image.attached? %>
            <%= image_tag user.profile_image, style: 'height:60px;width:60px;' %>
         <!-- show image if attached, if not use default-->
        <% else %>
	        <img src="https://d3pknrmpgdk5xi.cloudfront.net/assets/avatars/defaults/2-35169e7a0a76d93a0887f051aab8c51f02f050d919ff14a98dbc26179774b374.png" height="60" alt="<% user.username %>" class="nav-avatar">
        <% end %>
         <p><%= user.first_name %> <%= link_to('@' + user.username, view_profile_path(user.username), class: 'ok') %> </p>
    </div>
    </div>
    <br>
<% end %>

</body>
</html>

app/views/users/more_info.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= content_for :title,  'Winterworks | ' + 'More About ' + @user.first_name + ' (@' + @user.username + ')' %></title>
    <%= stylesheet_link_tag 'users' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>

<%= render 'shared/navbar' %>

<h1>About <%= @user.first_name %> (@<%= @user.username%>)</h1>

<% if @profile.about_desc == nil %>
<p>About description: Nothing here yet</p>
<% else %>
<p>About description: <%= @profile.about_desc %></p>
<% end %>

<% if @profile.work_exp == nil %>
<p>Work experience: Nothing here yet</p>
<% else %>
<p>Work experience: <%= @profile.work_exp %></p>
<% end %>

</body>
</html>

app/views/users/notifications.html.erb
<h1>Notifications</h1>

app/views/users/requests.html.erb
<%= render 'shared/navbar' %>

<h1>Discover Talent</h1>
<p>a collection of users taking comission requests</p>

<!-- coming soon: a href="#">filter button here</a><br> -->
<br>

<!-- if user.profile.taking_requests? -->

<% @users.each do |user| %>

 <% if user.profile.taking_requests? %>

<li> this user (@<%= user.username%>) is taking requests right now</li>

<% else %>
    <li>this user (@<%= user.username %>) is not taking any requests </li>
 <% end %>

<% end %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= content_for :title, @user.first_name + '\'s profile on Winterworks' %></title>
    <%= stylesheet_link_tag 'users' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>

<%= render 'shared/navbar' %>


<br>

<div style="text-align:center;">

<!-- show image if attached, if not use default-->
<% if @user.profile_image.attached? %>
	<%= image_tag @user.profile_image, style: 'height:80px;width:80px;' %>
<% else %>
	<img src="https://d3pknrmpgdk5xi.cloudfront.net/assets/avatars/defaults/2-35169e7a0a76d93a0887f051aab8c51f02f050d919ff14a98dbc26179774b374.png" height="80" alt="<% @user.username %>" class="nav-avatar">
<% end %>

		<div class="userprofile-heading">
		<h1><%= @user.first_name %> <%= @user.last_name %> 
		<% if @user.admin? %>
			<!-- show admin badge -->
			<span class="admin-badge">Admin</span>
		<% end %>
		</h1>

		<% if @user != current_user %>
			<% if @z == nil %>
				<%= button_to 'Follow', follow_this_user_path(@user.username), :method => :post %>
			<% else %>
				<%= button_to 'Unfollow', follow_this_user_path(@user.username), :method => :post %>
			<% end %>
		<% end %>
		
		</div>
		<p><%= link_to('@' + @user.username, view_profile_path(@user.username), class: 'ok') %> </p>
		<p><%= link_to('About ' + @user.first_name, about_profile_path(@user.username)) %></p>
		<br>
		<!-- BIO -->
		<% if @user.bio == nil %>
			Bio: Nothing here yet
			<br>
		<% else %>
			<p>Bio: <%= @user.bio %></p>
		<% end %>

		<!-- LOCATION -->
		<% if @user.location == nil %>
			Location: Presumably the internet?
			<br>
		<% else %>
			<p>Location: <%= @user.location %></p>
		<% end %>

		<!-- WEBSITE -->
		<% if @user.website == nil %>
			Website: Nothing linked yet?
		<% else %>	
			<p>Website: <a href="<%= @user.website %>"><%= @user.website %></a></p>
		<% end %>

		<p><%= @user.profile.status %> </p> <br>

		<% if @user.profile.status == 1 %>
			<span class="status-badge">
			<p>This user is looking for work</p>
			</span>
		<% end %>

<!-- follow button, message button, projects, commission portfolio -->

<p>Following: <%= @user.following.count %></p>
<p>Followers: <%= @user.followers.count %></p>
<p>Likes: <%= @user.likes.count %></p>

<% if @user == current_user %>
		<br>
		<%= link_to('Edit your PROFILE', edit_profile_path) %>  
		<span><p><%= @user.member_type %> membership</p></span>
<% end %>

<% if @user.profile.taking_requests? %>
	<p>User is taking commissions!</p>
	<%= link_to('View ' + @user.username + '\'s commission page', view_user_commission_page_path(@user.username)) %>
<% else %>
	<p>User is not taking commissions at this time.</p>
<% end %>


<% if @user.projects.any? %>
	Projects (<%= @user.projects.count %>)
<% end %>

  <% unless @user.posts.any? %>
  <h1>Portfolio</h1>
        @<%= @user.username %> has no posts...yet <br>
    <% else %>
		<h1>Posts</h1>
        <% @user.posts.each do |post| %>
		    <% if post.post_image.attached? %>
        	<div class="user-post-card">
			<% if post.post_type == "image" %>
				
				Posted by: @<%= post.user.username %> 
            	<li><%= post.title %></li>
				<%= image_tag post.post_image, style: 'height:40px;width:40px;' %> <br> 
            	<li><%= post.date_posted %></li>
            	<li><%= post.description %></li>
			<% else %>
				<li>this is a audio and or video post, currently not previewable</li>
			<% end %>
        </div>
			<% end %>

        <% end %>
            <!-- if user has posts show them -->
    <% end %>
</div>
</body>
<html>