config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/dev-admin', as: 'rails_admin'
  ActiveAdmin.routes(self)
  /# Implement subdomain for blog #/

  # constraints Subdomain do ----> 'Blog'
  # get "/" => redirect { |params| "http://www.winterworks.com" }
  # get '*path' => redirect('/')
  # get '*path#*path' => redirect('/')
  # end

  # admin routes

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
}, skip: [:sessions, :registrations]


  root :to => "index#default"
  get '/dashboard/' => 'users#index', :as => 'user_root' # manage projects from here? idk yet -- definitely view orders and stuff

  # Devise 

  devise_scope :user do

    ## MARK: Add custom forget password button

    get    'register', to: 'devise/registrations#new',    as: :new_user_registration
    post   '/account',  to: 'devise/registrations#create'
    get    '/account/cancel', to: 'devise/registrations#cancel', as: :cancel_user_registration

    get    '/account',  to: 'devise/registrations#edit',   as: :edit_user_registration
    put    '/account',  to: 'devise/registrations#update'
    patch  '/account',  to: 'devise/registrations#update', as: :user_registration
    delete '/account',  to: 'devise/registrations#destroy'
    
    get    'login',  to: 'devise/sessions#new',     as: :new_user_session
    post   'login',  to: 'devise/sessions#create',  as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  # Extraneous routes --> Static

  get '/pricing/' => 'index#pricing', as: 'pricing'
  get '/about/' => 'index#about', as: 'about'
  get '/blog/' => 'index#blog', as: 'view_blog'
  get '/support/' => 'index#support', as: 'support'

  # Extraneous routes --> Dynamic/Static

  get '/browse/' => 'index#discover', as: 'social_feed'
  get '/browse/posts/' => 'posts#list_global', as: 'posts_feed'

  get '/browse/users/' => 'users#list', as: 'list_users'
  get '/browse/talent/' => 'users#requests', as: 'hireable_users'

  # Extraneous routes --> Project Management

  get '/browse/projects/:q' => "projects#filter_by_project_type", :as => 'filter_proj_by_type'
  
  match '/edit-project/:uuid/:id' => 'edit_project#show', :via => [:get], as: 'edit_project'


  get '/browse/projects/' => 'projects#feed', as: 'view_projects'
  get '/new/project/' => 'projects#new', as: 'create_new_project'
  post '/submit/project/' => 'projects#create', as: 'submit_new_project'
  match '/project/:uuid/' => 'projects#view', :via => [:get], as: 'view_singular_project'

  # Extraneous routes --> Commission Management

  match '/@:username/commission/:uuid/' => 'commissions#view', :via => [:get], as: 'view_singular_commission'
  get '/browse/commissions/' => 'commissions#list', as: 'list_commissions'
  get '/new/commissions/' => 'commissions#create', as: 'create_new_commission'
  post '/submit/commission/' => 'commissions#new', as: 'submit_new_commission'

  # Extraneous routes --> Upload, Creation + Onboarding

  get '/submit/' => 'posts#upload', as: 'upload_post'
  post '/submit/' => 'posts#new', as: 'submit_new_post'
  match '/posts/:uuid/' => 'posts#view', :via => [:get], as: 'view_this_post'
  match '/posts/:uuid/like' => 'posts#like', :via => [:post], as: 'like_post'
  match '/posts/:uuid/comment' => 'comments#create', :via => [:post], as: 'create_new_comment'

  # Extraneous routes --> Public User Showcase
  match '/@:username/follow' => 'followerships#follow_user', :via => [:post], as: 'follow_this_user'


  match '/@:username/following' => 'followerships#following', :via => [:get], as: 'user_following'
  match '/@:username/followers' => 'followerships#followers', :via => [:get], as: 'user_followers'
  match '/@:username/likes' => 'users#list_likes', :via => [:get], as: 'list_this_users_likes'


  match '/@:username' => 'users#show', :via => [:get], as: 'view_profile'
  match '/@:username/about' => 'users#more_info', :via => [:get], as: 'about_profile'

  get '/profile/edit/' => 'users#edit_profile', as: 'edit_profile'
  patch '/profile/edit/' => 'users#update_profile', as: 'update_profile'

  get '/i/notifications/' => 'users#notifications', as: 'social_notifications'

  # Extraneous routes --> Commissions

  match '/@:username/portfolio/' => 'portfolio#show', :via => [:get], as: 'view_user_commission_page'
  match '/@:username/portfolio/edit/' => 'portfolio#edit', :via => [:get], as: 'edit_user_commission_page'
  match '/@:username/portfolio/edit/' => 'portfolio#update', :via => [:patch], as: 'update_user_commission_page'
  
  # Extraneous routes --> Manufactory Checkout
  
  resources :manufactory

  # Extraneous routes --> Orders

  match '/checkout/commission/:uuid/:id' => 'orders#new', :via => [:get], as: 'place_new_commission_order'

  # Extraneous routes --> Dynamic Project Space

  # Extraneous routes --> Payments

  get '/account/billing', to: 'users#payments', as: 'edit_billing_methods'

end

app/views/shared/_filtered_projects_by_type.html.erb
<!Doctype html>
<html>
<head>
    <%= stylesheet_link_tag 'shared/nav_bar' %>
</head>
<body>
<%= render 'shared/navbar' %>

<br>
<div>
<%= link_to create_new_project_path, class: 'filled-btn' do %>New Project<% end %>
</div>

<h1>Discover projects</h1>

<p>a collection of active projects, coming soon</p>

<a href="#">filter button here</a><br>

<br>

<% if @projects.empty? %>
    No projects match this criteria (empty)
<% end %>


<% if @projects.where(is_published: false) %>
    No projects match this criteria (none published)
<% else %>
    <% @projects.each do |p| %>
        <% if p.project_type = @query %>
            <!-- if user has posts show them -->
            <li><%= p.title %></li>
            <%= link_to "View this project", view_singular_project_path(p.uuid) %>
        <% end %>
    <% end %> 
<% end %>
</body>
</html>

app/views/shared/_navbar.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= stylesheet_link_tag 'shared/nav_bar' %>
    <script
        src="https://code.jquery.com/jquery-3.3.1.slim.js"
        integrity="sha256-fNXJFIlca05BIO2Y5zh1xrShK3ME+/lYZ0j+ChxX2DA="
        crossorigin="anonymous">
    </script>
    <%= javascript_include_tag "index" %>
    <script>
    // index.js

$(document).ready(function(){
    $('.nav-right-side img').on('click', () => {
        console.log("clicked");
        if ($('#navbar .wrap .nav-right-side .dropdown-menu').hasClass('active')) {
            // if it already has, remove it and make the menu invisible
            $('#navbar .wrap .nav-right-side .dropdown-menu').removeClass('active');
            $('#navbar .wrap .nav-right-side .dropdown-menu').css({'display': ''});
            $('#navbar .wrap .nav-right-side .dropdown-menu').css({'display': 'none'});

            next();
        } else {
            console.log("twice clicked");
            // if it doesn't, add the class and make the menu visible
            $('#navbar .wrap .nav-right-side .dropdown-menu').addClass('active');
            $('#navbar .wrap .nav-right-side .dropdown-menu').css({'display': ''});
            $('#navbar .wrap .nav-right-side .dropdown-menu').css({"display": "block"});

            next();
        };
    });
});


</script>
</head>
<body>

<!-- NAV BAR -->

<div id="navbar">
    <div class="wrap">

        <div class="nav-left-side">
            <div class="header">
                <%= link_to "Winterworks", root_path, class: 'nil' %>
             <!-- MARK: DEPRECRATED   <span class="header-beta-span">beta</span> -->
            </div>
        </div>

        <div class="nav-mid-side">
            <div class="nav-links">
                <ul>
                    <li><%= link_to "About", about_path %></li>
                    <li><%= link_to "Pricing", pricing_path %></li>
                    <li><%= link_to "Manufactory", manufactory_path(:select_services) %></li>

                    <li><%= link_to "Discover", social_feed_path %></li>

                    <li><%= link_to "Projects", view_projects_path %></li>
                    <li><%= link_to "Talent", hireable_users_path %></li>
                    <li><%= link_to "Commissions", list_commissions_path %></li> 

                    <!-- <li><%= link_to "Blog", view_blog_path %></li> -->

                </ul>
            </div>
        </div>



        <% if current_user.nil? %> 
        <div class="nav-right-side"> 
            <%= link_to "Sign Up", new_user_registration_path, class: 'filled-btn' %> <br>
            <%= link_to "Log In", new_user_session_path, class: 'vacant-btn' %>
            <a href="#" class="nav-burger-menu">burger</a>
        </div>
        <% end %>

        <% if user_signed_in? %>
            <div class="nav-right-side">
            <% if current_user.profile_image.attached? %>
                <%= image_tag current_user.profile_image, style: 'height:60px;width:60px;border: 4px solid #ffffff;box-shadow: 0 1px 5px 0 rgba(93,118,194,0.5);border-radius: 100%;', class: "nav_user_img" %>
            <% else %>
                <a href="<%= view_profile_path(current_user.username) %>">
	            <img src="https://d3pknrmpgdk5xi.cloudfront.net/assets/avatars/defaults/2-35169e7a0a76d93a0887f051aab8c51f02f050d919ff14a98dbc26179774b374.png" style='height:60px;width:60px;border: 4px solid #ffffff;box-shadow: 0 1px 5px 0 rgba(93,118,194,0.5);border-radius: 100%;' alt="<% current_user.username %>" class="nav-avatar">
                </a>
            <% end %>

            <ul class="dropdown-menu">
                <li><%= link_to 'My Profile', view_profile_path(current_user.username), {:class => 'profile-picture-link'} %></li>
                <li><%= link_to 'My Projects', view_projects_path %></li>
                <li><%= link_to 'Upload art', upload_post_path %></li>
                <li><%= link_to 'Go to Dashboard', user_root_path %></li>
                <li><%= link_to 'Support', support_path %></li>
                <li><%= link_to "Log out", destroy_user_session_path, :method => :delete, class: 'logout' %></li>
            </ul>
            <!--

                Support
                My Projects
                <%= link_to 'Upload art', upload_post_path %>
                <%= link_to user_root_path, class: 'filled-btn' do %>Go to Dashboard!<% end %>
            -->
        </div>
    <% end %>

    </div>
</div>

<!-- PAGE ART -->

<div class="page__art">
        <div class="art-wrapper">
            <div class="art"></div>
        </div>
</div>

</body>
</html>

app/views/shared/_projbar.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= stylesheet_link_tag 'shared/proj_bar' %>
    <script
        src="https://code.jquery.com/jquery-3.3.1.slim.js"
        integrity="sha256-fNXJFIlca05BIO2Y5zh1xrShK3ME+/lYZ0j+ChxX2DA="
        crossorigin="anonymous">
    </script>
</head>
<body>

    <% if @user.id == @owner.id %>

    <div id="nav_bar">

        <%= @project.title %>

        <ul>
            <li><%= link_to 'Overview', view_singular_project_path %></li>
            <li>Feed</li>
            <li>Chat</li>
            <li>Files</li>
            <li>Tasks</li>
            <li>Members</li>
        </ul>
    </div>
    <% else %>
       My projects <!-- this is not your project -->
        <ul>
            <li><%= link_to 'Overview', view_singular_project_path %></li>
            <li>Members</li>
        </ul>
    <% end %>
<div class="page__background"></div>
</body>