config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/dev-admin', as: 'rails_admin'
  ActiveAdmin.routes(self)
  /# Implement subdomain for blog #/

  # constraints Subdomain do ----> 'Blog'
  # get "/" => redirect { |params| "http://www.winterworks.com" }
  # get '*path' => redirect('/')
  # get '*path#*path' => redirect('/')
  # end

  # admin routes

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
}, skip: [:sessions, :registrations]


  root :to => "index#default"
  get '/dashboard/' => 'users#index', :as => 'user_root' # manage projects from here? idk yet -- definitely view orders and stuff

  # Devise 

  devise_scope :user do

    ## MARK: Add custom forget password button

    get    'register', to: 'devise/registrations#new',    as: :new_user_registration
    post   '/account',  to: 'devise/registrations#create'
    get    '/account/cancel', to: 'devise/registrations#cancel', as: :cancel_user_registration

    get    '/account',  to: 'devise/registrations#edit',   as: :edit_user_registration
    put    '/account',  to: 'devise/registrations#update'
    patch  '/account',  to: 'devise/registrations#update', as: :user_registration
    delete '/account',  to: 'devise/registrations#destroy'
    
    get    'login',  to: 'devise/sessions#new',     as: :new_user_session
    post   'login',  to: 'devise/sessions#create',  as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  # Extraneous routes --> Static

  get '/pricing/' => 'index#pricing', as: 'pricing'
  get '/about/' => 'index#about', as: 'about'
  get '/blog/' => 'index#blog', as: 'view_blog'
  get '/support/' => 'index#support', as: 'support'

  # Extraneous routes --> Dynamic/Static

  get '/browse/' => 'index#discover', as: 'social_feed'
  get '/browse/posts/' => 'posts#list_global', as: 'posts_feed'

  get '/browse/users/' => 'users#list', as: 'list_users'
  get '/browse/talent/' => 'users#requests', as: 'hireable_users'

  # Extraneous routes --> Project Management

  get '/browse/projects/:q' => "projects#filter_by_project_type", :as => 'filter_proj_by_type'
  
  match '/edit-project/:uuid/:id' => 'edit_project#show', :via => [:get], as: 'edit_project'


  get '/browse/projects/' => 'projects#feed', as: 'view_projects'
  get '/new/project/' => 'projects#new', as: 'create_new_project'
  post '/submit/project/' => 'projects#create', as: 'submit_new_project'
  match '/project/:uuid/' => 'projects#view', :via => [:get], as: 'view_singular_project'

  # Extraneous routes --> Commission Management

  match '/@:username/commission/:uuid/' => 'commissions#view', :via => [:get], as: 'view_singular_commission'
  get '/browse/commissions/' => 'commissions#list', as: 'list_commissions'
  get '/new/commissions/' => 'commissions#create', as: 'create_new_commission'
  post '/submit/commission/' => 'commissions#new', as: 'submit_new_commission'

  # Extraneous routes --> Upload, Creation + Onboarding

  get '/submit/' => 'posts#upload', as: 'upload_post'
  post '/submit/' => 'posts#new', as: 'submit_new_post'
  match '/posts/:uuid/' => 'posts#view', :via => [:get], as: 'view_this_post'
  match '/posts/:uuid/like' => 'posts#like', :via => [:post], as: 'like_post'
  match '/posts/:uuid/comment' => 'comments#create', :via => [:post], as: 'create_new_comment'

  # Extraneous routes --> Public User Showcase
  match '/@:username/follow' => 'followerships#follow_user', :via => [:post], as: 'follow_this_user'


  match '/@:username/following' => 'followerships#following', :via => [:get], as: 'user_following'
  match '/@:username/followers' => 'followerships#followers', :via => [:get], as: 'user_followers'
  match '/@:username/likes' => 'users#list_likes', :via => [:get], as: 'list_this_users_likes'


  match '/@:username' => 'users#show', :via => [:get], as: 'view_profile'
  match '/@:username/about' => 'users#more_info', :via => [:get], as: 'about_profile'

  get '/profile/edit/' => 'users#edit_profile', as: 'edit_profile'
  patch '/profile/edit/' => 'users#update_profile', as: 'update_profile'

  get '/i/notifications/' => 'users#notifications', as: 'social_notifications'

  # Extraneous routes --> Commissions

  match '/@:username/portfolio/' => 'portfolio#show', :via => [:get], as: 'view_user_commission_page'
  match '/@:username/portfolio/edit/' => 'portfolio#edit', :via => [:get], as: 'edit_user_commission_page'
  match '/@:username/portfolio/edit/' => 'portfolio#update', :via => [:patch], as: 'update_user_commission_page'
  
  # Extraneous routes --> Manufactory Checkout
  
  resources :manufactory

  # Extraneous routes --> Orders

  match '/checkout/commission/:uuid/:id' => 'orders#new', :via => [:get], as: 'place_new_commission_order'

  # Extraneous routes --> Dynamic Project Space

  # Extraneous routes --> Payments

  get '/account/billing', to: 'users#payments', as: 'edit_billing_methods'

end

app/models/project.rb
# rails g model project title:string project_type:integer category:integer user:references
# rails g migration AddAccessColumnsToProject date_posted:date is_published:boolean
# rails g migration AddStatusSettingsToProject status:integer
# rails g migration AddUUIDToProject uuid:string

class Project < ApplicationRecord
  belongs_to :user
  # Titles for project types
  enum project_type: { Volunteer: 2, Hobby: 1, Funded: 0}
  # Titles for categories
  enum category: { Action:4, Horror: 3, Anime: 2, Fairytale: 1, Scifi: 0}
  # Titles for status settings
  enum status: {"Final Editing": 4, "Post Production": 3, Production:2, "Pre-Production": 1, Development: 0}

    # Validations

    validates(:date_posted, presence: true)    

    validates(:uuid, presence: true, :uniqueness => {:message => "This project already exists."})

    validates(:status, presence: true)

    validates(:project_type, presence: true)

    validates(:category, presence: true)
  
    validates(:title, presence: true, length: 5..55)
end

app/controllers/projects_controller.rb
# rails g controller projects

class ProjectsController < ApplicationController
    skip_before_action :authenticate_user!, :only => [:feed, :view]

    def feed
        @user = current_user
        @users = User.all
        @projects = Project.all
    end

    def new
        @user = current_user
        @project = @user.projects.new
    end

    def create
        @user = current_user
        @project = @user.projects.create(project_params)

        @project.date_posted = DateTime.now.to_date
        @project.user_id = @user.id
        @project.uuid = SecureRandom.uuid

        if @project.save
            redirect_to view_singular_project_path(@project.uuid), notice: 'This is your new project.'
        else
            redirect_to create_new_commission_path, notice: 'Missing required attributes for a new project, please try again!'
        end
    end

    def view
        @user = current_user
        @project = Project.find_by_uuid(params[:uuid])
        @owner = Project.find_by_uuid(params[:uuid]).user
    end

    def filter_by_project_type
        #render :nothing => true
        # head :ok
        @q = params[:q]
        if @q == 'Volunteer' || 'volunteer'
            @query = 2
            @projects = Project.where(:project_type => @query).all #.all
            render 'shared/_filtered_projects_by_type'
        elsif @q == 'Hobby' || 'hobby'
            @query = 1
            @projects = Project.where(:project_type => @query).all #.all
            render 'shared/_filtered_projects_by_type'
        elsif @q == 'Funded' || 'funded'
            @query = 0
            @projects = Project.where(:project_type => @query).all #.all
            render 'shared/_filtered_projects_by_type'
        else
            puts 'fukck'
        end
    end

    private

    def project_owner_params
        params.require(:project).permit(:user_id)
    end

    def project_params
      params.require(:project).permit(:title, :project_type, :category, :user_id, :is_published, :date_posted, :uuid)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/feed.html.erb
<%= render 'shared/navbar' %>

<br>
<div>
<%= link_to create_new_project_path, class: 'filled-btn' do %>New Project<% end %>
</div>

<h1>Featured projects</h1>

<p>a collection of active projects, coming soon</p>

<!-- coming soon: a href="#">filter button here</a><br> -->

<br>

<% if @projects.empty? || @projects.where(is_published: false) %>
    No public projects yet
<% end %>

<% @users.each do |user| %>

        <% user.projects.each do |pj| %>
            <% if pj.is_published? %>
            <!-- if user has posts show them -->
               <li><%= pj.title %></li>
               <%= link_to "View this project", view_singular_project_path(pj.uuid) %>
            <% end %>
        <% end %>
<% end %>

app/views/projects/new.html.erb
<%= render 'shared/navbar' %>

<h1>Create a new project </h1>

<%= form_for(@project, url: submit_new_project_path, local: true) do |f| %>

    <%= f.label :project_type %>
    <%= f.select :project_type, Project.project_types.keys, {}, { :class => 'my_style_class' }  %> 

    <br>

    <%= f.label :category %>
    <%= f.select :category, Project.categories.keys, {}, { :class => 'my_style_class' }  %> 

    <br>

    <%= f.label :status %>
    <%= f.select :status, Project.statuses.keys, {}, { :class => 'my_style_class' }  %> 

    <%= f.hidden_field :is_published, :value => false %>

    <%= f.label :title %>:
    <%= f.text_field :title, class: 'form-control' %>
    
    <br>

    <br>

    <%= f.submit "Create a new project"%>
<% end %>

app/views/projects/view.html.erb
<!-- render both bars, hidden on click -->

<%= render 'shared/navbar' %>
<%= render 'shared/projbar' %>



<%= link_to "Return to all projects", view_projects_path %>

<% if @project.is_published == false %>
    <% if @user.id == @owner.id %>
		<br>
        This is a draft!
		<%= link_to 'Prepare for publishing', edit_project_path(@project.uuid, :details) %>
    <% else %>
        <% controller.redirect_to root_path, notice: 'Project is in draft mode and invisible, redirect!' %>
    <% end %>

<% else %>
    THIS PROJECT IS PUBLISHED
<% end %>

<h1><%= @owner.username%>'s project</h1>

<% if @user.id == @owner.id %>
    <h3><%= @project.title %></h3> <br>
    u own this project
<% else %>
    <% if @project.is_published? %>
        <h3><%= @project.title %></h3> <br>
        <%= @project.project_type %> <br>
        <%= @project.category %> <br>
        <%= @project.status %> <br>
        <%= link_to "Request to join this project", view_projects_path %>
    <% else %>
        This project is not published yet.
    <% end %>
<% end %>